APP_NAME = "dynamic_rest"
AUTHOR = "Anthony Leontiev"
AUTHOR_EMAIL = "ant@altschool.com"
DESCRIPTION = "Adds Dynamic API support to Django REST Framework."
REPO_NAME = "dynamic-rest"
ORG_NAME = "AltSchool"
VERSION = "1.3.10"
