# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-22 16:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cat',
            name='is_dead',
            field=models.NullBooleanField(default=False),
        ),
    ]
