# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-18 04:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0005_auto_20161117_0645'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='preferred_group',
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE,
                to='tests.Group'),
        )
    ]
