# flake8: noqa
# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-31 19:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0005_auto_20170712_0759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tests.Country'),
        ),
    ]
